name: Build and publish to pages
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Build site
        run: |
          chmod +x ./publishWeb.sh
          ./publishWeb.sh

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: success()
        with:
          github_token: ${{ secrets.API_TOKEN_GITHUB }}
          publish_dir: ./public
